// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;

    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AgregarPagosPedidoMuestra : IMigrationMetadata
    {
        string IMigrationMetadata.Id => "202511130321119_AgregarPagosPedidoMuestra";

        string IMigrationMetadata.Source => null;

        string IMigrationMetadata.Target => null;
    }
}